// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/etask/internal/agent"
	grpc2 "github.com/Duke1616/etask/internal/grpc"
	"github.com/Duke1616/etask/internal/repository"
	"github.com/Duke1616/etask/internal/repository/dao"
	"github.com/Duke1616/etask/internal/service/codebook"
	"github.com/Duke1616/etask/internal/service/pool"
	"github.com/Duke1616/etask/internal/service/runner"
	"github.com/Duke1616/etask/internal/service/task"
	"github.com/Duke1616/etask/internal/service/task/binding"
	"github.com/Duke1616/etask/internal/service/variable"
	codebook2 "github.com/Duke1616/etask/internal/web/codebook"
	"github.com/Duke1616/etask/internal/web/manager"
	pool2 "github.com/Duke1616/etask/internal/web/pool"
	"github.com/Duke1616/etask/internal/web/resource"
	runner2 "github.com/Duke1616/etask/internal/web/runner"
	variable2 "github.com/Duke1616/etask/internal/web/variable"
	"github.com/Duke1616/etask/pkg/grpc"
	"github.com/Duke1616/etask/sdk/executor"
)

// Injectors from wire.go:

// InitBase 初始化所有共享基础设施（建立连接，但不运行业务）
func InitBase() *Base {
	client := InitEtcdClient()
	registry := InitRegistry(client)
	mq := InitMQ()
	base := &Base{
		Registry: registry,
		MQ:       mq,
		Etcd:     client,
	}
	return base
}

// InitSchedulerModule 专门用于构造 Scheduler 模块及其配套后台任务
func InitSchedulerModule(base *Base) *SchedulerModule {
	string2 := InitNodeID()
	db := InitDB()
	taskDAO := dao.NewGORMTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	executionPoolDAO := dao.NewGORMExecutionPoolDAO(db)
	executionPoolRepository := repository.NewExecutionPoolRepository(executionPoolDAO)
	executionPoolBindingDAO := dao.NewGORMExecutionPoolBindingDAO(db)
	executionPoolBindingRepository := repository.NewExecutionPoolBindingRepository(executionPoolBindingDAO)
	bindingService := pool.NewBindingService(executionPoolRepository, executionPoolBindingRepository)
	service := task.NewService(taskRepository, bindingService)
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(db)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO)
	taskExecutionLogDAO := dao.NewGORMTaskExecutionLogDAO(db)
	taskExecutionLogRepository := repository.NewTaskExecutionLogRepository(taskExecutionLogDAO)
	logService := task.NewLogService(taskExecutionLogRepository)
	mq := base.MQ
	completeProducer := InitCompleteProducer(mq)
	registry := base.Registry
	codebookDAO := dao.NewGORMCodebookDAO(db)
	codebookProjectDAO := dao.NewGORMCodebookProjectDAO(db)
	iCodebookRepository := repository.NewCodebookRepository(codebookDAO, codebookProjectDAO)
	codebookService := codebook.NewService(iCodebookRepository)
	runnerDAO := dao.NewGORMRunnerDAO(db)
	variableDAO := dao.NewGORMVariableDAO(db)
	crypto := InitCrypto()
	runnerRepository := repository.NewRunnerRepository(runnerDAO, variableDAO, crypto)
	runnerService := runner.NewService(runnerRepository)
	bindingResolverRegistry := binding.NewScriptBindingResolvers(codebookService, runnerService)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, logService, completeProducer, registry, bindingResolverRegistry)
	taskAcquirer := InitMySQLTaskAcquirer(taskRepository)
	clients := InitExecutorServiceGRPCClients(registry)
	invoker := InitInvoker(clients)
	dispatcher := InitDispatcher(string2, service, executionService, taskAcquirer, invoker, completeProducer)
	executorNodePicker := InitExecutorNodePicker(registry)
	iExecModeResolver := InitExecModeResolver(registry, taskRepository)
	scheduler := InitScheduler(string2, dispatcher, service, executionService, taskAcquirer, executorNodePicker, iExecModeResolver)
	retryCompensator := InitRetryCompensator(dispatcher, executionService)
	rescheduleCompensator := InitRescheduleCompensator(dispatcher, executionService)
	interruptCompensator := InitInterruptCompensator(clients, executionService)
	completeConsumer := InitCompleteEventConsumer(mq, service, executionService, taskAcquirer)
	client := base.Etcd
	syncer := pool.NewSyncer(executionPoolRepository, client)
	v := InitTasks(retryCompensator, rescheduleCompensator, interruptCompensator, completeConsumer, syncer)
	schedulerModule := &SchedulerModule{
		Svc:   scheduler,
		Tasks: v,
	}
	return schedulerModule
}

// InitExecutorModule 专门用于构造原生执行器模块
func InitExecutorModule(base *Base) *executor.Executor {
	client := base.Etcd
	executorExecutor := InitExecutor(client)
	return executorExecutor
}

// InitAgentModule 专门用于构造异步代理模块 (包含 Kafka 消费者)
func InitAgentModule(base *Base) *agent.Module {
	mq := base.MQ
	client := base.Etcd
	module := agent.InitModule(mq, client)
	return module
}

// InitSchedulerServerModule 构造调度中心的 gRPC 服务端 (负责接收上报、下发任务及服务注册)
func InitSchedulerServerModule(base *Base) *grpc.Server {
	registry := base.Registry
	string2 := InitNodeID()
	db := InitDB()
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(db)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO)
	taskDAO := dao.NewGORMTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	executionPoolDAO := dao.NewGORMExecutionPoolDAO(db)
	executionPoolRepository := repository.NewExecutionPoolRepository(executionPoolDAO)
	executionPoolBindingDAO := dao.NewGORMExecutionPoolBindingDAO(db)
	executionPoolBindingRepository := repository.NewExecutionPoolBindingRepository(executionPoolBindingDAO)
	bindingService := pool.NewBindingService(executionPoolRepository, executionPoolBindingRepository)
	service := task.NewService(taskRepository, bindingService)
	taskExecutionLogDAO := dao.NewGORMTaskExecutionLogDAO(db)
	taskExecutionLogRepository := repository.NewTaskExecutionLogRepository(taskExecutionLogDAO)
	logService := task.NewLogService(taskExecutionLogRepository)
	mq := base.MQ
	completeProducer := InitCompleteProducer(mq)
	codebookDAO := dao.NewGORMCodebookDAO(db)
	codebookProjectDAO := dao.NewGORMCodebookProjectDAO(db)
	iCodebookRepository := repository.NewCodebookRepository(codebookDAO, codebookProjectDAO)
	codebookService := codebook.NewService(iCodebookRepository)
	runnerDAO := dao.NewGORMRunnerDAO(db)
	variableDAO := dao.NewGORMVariableDAO(db)
	crypto := InitCrypto()
	runnerRepository := repository.NewRunnerRepository(runnerDAO, variableDAO, crypto)
	runnerService := runner.NewService(runnerRepository)
	bindingResolverRegistry := binding.NewScriptBindingResolvers(codebookService, runnerService)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, logService, completeProducer, registry, bindingResolverRegistry)
	reporterServer := grpc2.NewReporterServer(executionService)
	taskServer := grpc2.NewTaskServer(service)
	agentServer := grpc2.NewAgentServer(taskExecutionRepository, executionService, logService, bindingService)
	codebookServer := grpc2.NewCodebookServer(codebookService)
	runnerServer := grpc2.NewRunnerServer(runnerService)
	server := InitSchedulerNodeGRPCServer(registry, reporterServer, taskServer, agentServer, codebookServer, runnerServer)
	return server
}

func InitWebModule(base *Base) *WebModule {
	v := InitGinMiddlewares()
	sdk := InitPolicySDK()
	syncer := InitPermSyncer()
	v2 := InitProviders()
	db := InitDB()
	taskDAO := dao.NewGORMTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	executionPoolDAO := dao.NewGORMExecutionPoolDAO(db)
	executionPoolRepository := repository.NewExecutionPoolRepository(executionPoolDAO)
	executionPoolBindingDAO := dao.NewGORMExecutionPoolBindingDAO(db)
	executionPoolBindingRepository := repository.NewExecutionPoolBindingRepository(executionPoolBindingDAO)
	bindingService := pool.NewBindingService(executionPoolRepository, executionPoolBindingRepository)
	service := task.NewService(taskRepository, bindingService)
	taskExecutionLogDAO := dao.NewGORMTaskExecutionLogDAO(db)
	taskExecutionLogRepository := repository.NewTaskExecutionLogRepository(taskExecutionLogDAO)
	logService := task.NewLogService(taskExecutionLogRepository)
	string2 := InitNodeID()
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(db)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO)
	mq := base.MQ
	completeProducer := InitCompleteProducer(mq)
	registry := base.Registry
	codebookDAO := dao.NewGORMCodebookDAO(db)
	codebookProjectDAO := dao.NewGORMCodebookProjectDAO(db)
	iCodebookRepository := repository.NewCodebookRepository(codebookDAO, codebookProjectDAO)
	codebookService := codebook.NewService(iCodebookRepository)
	runnerDAO := dao.NewGORMRunnerDAO(db)
	variableDAO := dao.NewGORMVariableDAO(db)
	crypto := InitCrypto()
	runnerRepository := repository.NewRunnerRepository(runnerDAO, variableDAO, crypto)
	runnerService := runner.NewService(runnerRepository)
	bindingResolverRegistry := binding.NewScriptBindingResolvers(codebookService, runnerService)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, logService, completeProducer, registry, bindingResolverRegistry)
	handler := manager.NewHandler(service, logService, executionService)
	codebookHandler := codebook2.NewHandler(codebookService)
	runnerHandler := runner2.NewHandler(runnerService)
	variableRepository := repository.NewVariableRepository(variableDAO, crypto)
	variableService := variable.NewService(variableRepository)
	variableHandler := variable2.NewHandler(variableService)
	catalogService := pool.NewCatalogService(executionPoolRepository, executionPoolBindingRepository)
	adminHandler := pool2.NewAdminHandler(bindingService, catalogService)
	resourceHandler := resource.NewHandler(catalogService)
	listener := InitListener()
	component := InitGinWebServer(v, sdk, syncer, v2, handler, codebookHandler, runnerHandler, variableHandler, adminHandler, resourceHandler, listener)
	webModule := &WebModule{
		Web: component,
	}
	return webModule
}
