// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/runner/runner.go
//
// Generated by this command:
//
//	mockgen -source=./internal/service/runner/runner.go -package=runnermocks -destination=./internal/service/runner/mocks/runner.mock.go -typed Service
//

// Package runnermocks is a generated GoMock package.
package runnermocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Duke1616/etask/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AggregateTags mocks base method.
func (m *MockService) AggregateTags(ctx context.Context) ([]domain.RunnerTags, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AggregateTags", ctx)
	ret0, _ := ret[0].([]domain.RunnerTags)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AggregateTags indicates an expected call of AggregateTags.
func (mr *MockServiceMockRecorder) AggregateTags(ctx any) *MockServiceAggregateTagsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AggregateTags", reflect.TypeOf((*MockService)(nil).AggregateTags), ctx)
	return &MockServiceAggregateTagsCall{Call: call}
}

// MockServiceAggregateTagsCall wrap *gomock.Call
type MockServiceAggregateTagsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceAggregateTagsCall) Return(arg0 []domain.RunnerTags, arg1 error) *MockServiceAggregateTagsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceAggregateTagsCall) Do(f func(context.Context) ([]domain.RunnerTags, error)) *MockServiceAggregateTagsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceAggregateTagsCall) DoAndReturn(f func(context.Context) ([]domain.RunnerTags, error)) *MockServiceAggregateTagsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Create mocks base method.
func (m *MockService) Create(ctx context.Context, req domain.Runner) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceMockRecorder) Create(ctx, req any) *MockServiceCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockService)(nil).Create), ctx, req)
	return &MockServiceCreateCall{Call: call}
}

// MockServiceCreateCall wrap *gomock.Call
type MockServiceCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceCreateCall) Return(arg0 int64, arg1 error) *MockServiceCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceCreateCall) Do(f func(context.Context, domain.Runner) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceCreateCall) DoAndReturn(f func(context.Context, domain.Runner) (int64, error)) *MockServiceCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *MockServiceDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
	return &MockServiceDeleteCall{Call: call}
}

// MockServiceDeleteCall wrap *gomock.Call
type MockServiceDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceDeleteCall) Return(arg0 int64, arg1 error) *MockServiceDeleteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceDeleteCall) Do(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceDeleteCall) DoAndReturn(f func(context.Context, int64) (int64, error)) *MockServiceDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByCodebookUIDAndTag mocks base method.
func (m *MockService) FindByCodebookUIDAndTag(ctx context.Context, codebookUID, tag string) (domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCodebookUIDAndTag", ctx, codebookUID, tag)
	ret0, _ := ret[0].(domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCodebookUIDAndTag indicates an expected call of FindByCodebookUIDAndTag.
func (mr *MockServiceMockRecorder) FindByCodebookUIDAndTag(ctx, codebookUID, tag any) *MockServiceFindByCodebookUIDAndTagCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCodebookUIDAndTag", reflect.TypeOf((*MockService)(nil).FindByCodebookUIDAndTag), ctx, codebookUID, tag)
	return &MockServiceFindByCodebookUIDAndTagCall{Call: call}
}

// MockServiceFindByCodebookUIDAndTagCall wrap *gomock.Call
type MockServiceFindByCodebookUIDAndTagCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindByCodebookUIDAndTagCall) Return(arg0 domain.Runner, arg1 error) *MockServiceFindByCodebookUIDAndTagCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindByCodebookUIDAndTagCall) Do(f func(context.Context, string, string) (domain.Runner, error)) *MockServiceFindByCodebookUIDAndTagCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindByCodebookUIDAndTagCall) DoAndReturn(f func(context.Context, string, string) (domain.Runner, error)) *MockServiceFindByCodebookUIDAndTagCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindByID mocks base method.
func (m *MockService) FindByID(ctx context.Context, id int64) (domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockServiceMockRecorder) FindByID(ctx, id any) *MockServiceFindByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockService)(nil).FindByID), ctx, id)
	return &MockServiceFindByIDCall{Call: call}
}

// MockServiceFindByIDCall wrap *gomock.Call
type MockServiceFindByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindByIDCall) Return(arg0 domain.Runner, arg1 error) *MockServiceFindByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindByIDCall) Do(f func(context.Context, int64) (domain.Runner, error)) *MockServiceFindByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindByIDCall) DoAndReturn(f func(context.Context, int64) (domain.Runner, error)) *MockServiceFindByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, offset, limit int64, keyword, kind string) ([]domain.Runner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, offset, limit, keyword, kind)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, offset, limit, keyword, kind any) *MockServiceListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, offset, limit, keyword, kind)
	return &MockServiceListCall{Call: call}
}

// MockServiceListCall wrap *gomock.Call
type MockServiceListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListCall) Return(arg0 []domain.Runner, arg1 int64, arg2 error) *MockServiceListCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListCall) Do(f func(context.Context, int64, int64, string, string) ([]domain.Runner, int64, error)) *MockServiceListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListCall) DoAndReturn(f func(context.Context, int64, int64, string, string) ([]domain.Runner, int64, error)) *MockServiceListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByCodebookUID mocks base method.
func (m *MockService) ListByCodebookUID(ctx context.Context, offset, limit int64, codebookUID, keyword, kind string) ([]domain.Runner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCodebookUID", ctx, offset, limit, codebookUID, keyword, kind)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByCodebookUID indicates an expected call of ListByCodebookUID.
func (mr *MockServiceMockRecorder) ListByCodebookUID(ctx, offset, limit, codebookUID, keyword, kind any) *MockServiceListByCodebookUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCodebookUID", reflect.TypeOf((*MockService)(nil).ListByCodebookUID), ctx, offset, limit, codebookUID, keyword, kind)
	return &MockServiceListByCodebookUIDCall{Call: call}
}

// MockServiceListByCodebookUIDCall wrap *gomock.Call
type MockServiceListByCodebookUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListByCodebookUIDCall) Return(arg0 []domain.Runner, arg1 int64, arg2 error) *MockServiceListByCodebookUIDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListByCodebookUIDCall) Do(f func(context.Context, int64, int64, string, string, string) ([]domain.Runner, int64, error)) *MockServiceListByCodebookUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListByCodebookUIDCall) DoAndReturn(f func(context.Context, int64, int64, string, string, string) ([]domain.Runner, int64, error)) *MockServiceListByCodebookUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByCodebookUIDs mocks base method.
func (m *MockService) ListByCodebookUIDs(ctx context.Context, codebookUIDs []string) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCodebookUIDs", ctx, codebookUIDs)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCodebookUIDs indicates an expected call of ListByCodebookUIDs.
func (mr *MockServiceMockRecorder) ListByCodebookUIDs(ctx, codebookUIDs any) *MockServiceListByCodebookUIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCodebookUIDs", reflect.TypeOf((*MockService)(nil).ListByCodebookUIDs), ctx, codebookUIDs)
	return &MockServiceListByCodebookUIDsCall{Call: call}
}

// MockServiceListByCodebookUIDsCall wrap *gomock.Call
type MockServiceListByCodebookUIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListByCodebookUIDsCall) Return(arg0 []domain.Runner, arg1 error) *MockServiceListByCodebookUIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListByCodebookUIDsCall) Do(f func(context.Context, []string) ([]domain.Runner, error)) *MockServiceListByCodebookUIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListByCodebookUIDsCall) DoAndReturn(f func(context.Context, []string) ([]domain.Runner, error)) *MockServiceListByCodebookUIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListByIDs mocks base method.
func (m *MockService) ListByIDs(ctx context.Context, ids []int64) ([]domain.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDs", ctx, ids)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDs indicates an expected call of ListByIDs.
func (mr *MockServiceMockRecorder) ListByIDs(ctx, ids any) *MockServiceListByIDsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDs", reflect.TypeOf((*MockService)(nil).ListByIDs), ctx, ids)
	return &MockServiceListByIDsCall{Call: call}
}

// MockServiceListByIDsCall wrap *gomock.Call
type MockServiceListByIDsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListByIDsCall) Return(arg0 []domain.Runner, arg1 error) *MockServiceListByIDsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListByIDsCall) Do(f func(context.Context, []int64) ([]domain.Runner, error)) *MockServiceListByIDsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListByIDsCall) DoAndReturn(f func(context.Context, []int64) ([]domain.Runner, error)) *MockServiceListByIDsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListExcludeCodebookUID mocks base method.
func (m *MockService) ListExcludeCodebookUID(ctx context.Context, offset, limit int64, codebookUID, keyword, kind string) ([]domain.Runner, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExcludeCodebookUID", ctx, offset, limit, codebookUID, keyword, kind)
	ret0, _ := ret[0].([]domain.Runner)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListExcludeCodebookUID indicates an expected call of ListExcludeCodebookUID.
func (mr *MockServiceMockRecorder) ListExcludeCodebookUID(ctx, offset, limit, codebookUID, keyword, kind any) *MockServiceListExcludeCodebookUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExcludeCodebookUID", reflect.TypeOf((*MockService)(nil).ListExcludeCodebookUID), ctx, offset, limit, codebookUID, keyword, kind)
	return &MockServiceListExcludeCodebookUIDCall{Call: call}
}

// MockServiceListExcludeCodebookUIDCall wrap *gomock.Call
type MockServiceListExcludeCodebookUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListExcludeCodebookUIDCall) Return(arg0 []domain.Runner, arg1 int64, arg2 error) *MockServiceListExcludeCodebookUIDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListExcludeCodebookUIDCall) Do(f func(context.Context, int64, int64, string, string, string) ([]domain.Runner, int64, error)) *MockServiceListExcludeCodebookUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListExcludeCodebookUIDCall) DoAndReturn(f func(context.Context, int64, int64, string, string, string) ([]domain.Runner, int64, error)) *MockServiceListExcludeCodebookUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListMergedVariables mocks base method.
func (m *MockService) ListMergedVariables(ctx context.Context, id int64) ([]domain.RunnerVariable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMergedVariables", ctx, id)
	ret0, _ := ret[0].([]domain.RunnerVariable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMergedVariables indicates an expected call of ListMergedVariables.
func (mr *MockServiceMockRecorder) ListMergedVariables(ctx, id any) *MockServiceListMergedVariablesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMergedVariables", reflect.TypeOf((*MockService)(nil).ListMergedVariables), ctx, id)
	return &MockServiceListMergedVariablesCall{Call: call}
}

// MockServiceListMergedVariablesCall wrap *gomock.Call
type MockServiceListMergedVariablesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceListMergedVariablesCall) Return(arg0 []domain.RunnerVariable, arg1 error) *MockServiceListMergedVariablesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceListMergedVariablesCall) Do(f func(context.Context, int64) ([]domain.RunnerVariable, error)) *MockServiceListMergedVariablesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceListMergedVariablesCall) DoAndReturn(f func(context.Context, int64) ([]domain.RunnerVariable, error)) *MockServiceListMergedVariablesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, req domain.Runner) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, req any) *MockServiceUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, req)
	return &MockServiceUpdateCall{Call: call}
}

// MockServiceUpdateCall wrap *gomock.Call
type MockServiceUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceUpdateCall) Return(arg0 int64, arg1 error) *MockServiceUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceUpdateCall) Do(f func(context.Context, domain.Runner) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceUpdateCall) DoAndReturn(f func(context.Context, domain.Runner) (int64, error)) *MockServiceUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
