// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package agent

import (
	"encoding/json"
	"github.com/Duke1616/etask/internal/agent/domain"
	"github.com/Duke1616/etask/internal/agent/event"
	"github.com/Duke1616/etask/internal/agent/service"
	"github.com/Duke1616/etask/internal/agent/web"
	"github.com/Duke1616/etask/pkg/grpc/registry"
	"github.com/Duke1616/etask/pkg/grpc/registry/etcd"
	"github.com/ecodeclub/mq-api"
	"github.com/google/uuid"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go.etcd.io/etcd/client/v3"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, etcdClient *clientv3.Client) *Module {
	serviceService := service.NewService(q)
	taskExecuteResultProducer := initExecuteProducer(q)
	registry := InitRegistry(etcdClient)
	executeConsumer := initExecuteConsumer(q, serviceService, taskExecuteResultProducer, registry)
	handler := web.NewHandler(etcdClient)
	module := &Module{
		Svc: serviceService,
		C:   executeConsumer,
		Hdl: handler,
	}
	return module
}

// wire.go:

type Instance struct {
	Name        string `yaml:"name" json:"name"`                 // 实例名称
	Desc        string `yaml:"desc" json:"desc"`                 // 注解
	Topic       string `yaml:"topic" json:"topic"`               // 建立 Topic 通道
	WorkerCount int    `yaml:"worker_count" json:"worker_count"` // 并发工作协程数量
}

var ProviderSet = wire.NewSet(service.NewService)

func initExecuteProducer(q mq.MQ) event.TaskExecuteResultProducer {
	producer, err := event.NewExecuteResultEventProducer(q)
	if err != nil {
		panic(err)
	}
	return producer
}

func InitRegistry(etcdClient *clientv3.Client) registry.Registry {
	reg, err := etcd.NewRegistryWithPrefix(etcdClient, "/etask/kafka")
	if err != nil {
		panic(err)
	}
	return reg
}

func initExecuteConsumer(q mq.MQ, svc service.Service, producer event.TaskExecuteResultProducer, reg registry.Registry) *event.ExecuteConsumer {
	var cfg Instance
	if err := viper.UnmarshalKey("agent", &cfg); err != nil {
		panic(err)
	}

	handlerMetas, _ := json.Marshal(svc.ListHandlers())
	instance := registry.ServiceInstance{
		Name:    domain.ServiceName,
		Address: uuid.New().String(),
		Metadata: map[string]any{
			"name":               cfg.Name,
			"desc":               cfg.Desc,
			"topic":              cfg.Topic,
			"supported_handlers": string(handlerMetas),
		},
	}

	consumer, err := event.NewExecuteConsumer(q, svc, cfg.Topic, producer, reg, instance, cfg.WorkerCount)
	if err != nil {
		panic(err)
	}

	return consumer
}
