// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package agent

import (
	"context"
	"encoding/json"
	"github.com/Duke1616/ework-runner/internal/agent/event"
	"github.com/Duke1616/ework-runner/internal/agent/service"
	"github.com/Duke1616/ework-runner/pkg/grpc/registry"
	"github.com/ecodeclub/mq-api"
	"github.com/google/uuid"
	"github.com/google/wire"
	"github.com/gotomicro/ego/core/elog"
	"github.com/spf13/viper"
	"time"
)

// Injectors from wire.go:

func InitModule(q mq.MQ, reg registry.Registry) *Module {
	serviceService := service.NewService(q)
	taskExecuteResultProducer := initExecuteProducer(q)
	executeConsumer := initExecuteConsumer(q, serviceService, taskExecuteResultProducer, reg)
	module := &Module{
		Svc: serviceService,
		C:   executeConsumer,
	}
	return module
}

// wire.go:

type Instance struct {
	Name  string `yaml:"name" json:"name"`   // 实例名称
	Desc  string `yaml:"desc" json:"desc"`   // 注解
	Topic string `yaml:"topic" json:"topic"` // 建立 Topic 通道
}

var ProviderSet = wire.NewSet(service.NewService)

func initExecuteProducer(q mq.MQ) event.TaskExecuteResultProducer {
	producer, err := event.NewExecuteResultEventProducer(q)
	if err != nil {
		panic(err)
	}
	return producer
}

func initExecuteConsumer(q mq.MQ, svc service.Service, producer event.TaskExecuteResultProducer, reg registry.Registry) *event.ExecuteConsumer {
	var cfg Instance
	if err := viper.UnmarshalKey("agent", &cfg); err != nil {
		panic(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
	defer cancel()

	handlerMetas, _ := json.Marshal(svc.ListHandlers())

	err := reg.Register(ctx, registry.ServiceInstance{
		Name:    ServiceName,
		Address: uuid.New().String(),
		Metadata: map[string]any{
			"name":               cfg.Name,
			"desc":               cfg.Desc,
			"topic":              cfg.Topic,
			"supported_handlers": string(handlerMetas),
		},
	})
	if err != nil {
		elog.Error("agent_register_failed", elog.FieldErr(err))
	}

	consumer, err := event.NewExecuteConsumer(q, svc, cfg.Topic, producer)
	if err != nil {
		panic(err)
	}

	return consumer
}
