// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/Duke1616/etask/ioc"
	"github.com/Duke1616/etask/pkg/grpc"
	"github.com/Duke1616/etask/sdk/executor"
)

// Injectors from wire.go:

// InitExecuteApp 该注入器支持原有的 executor 二进制启动，但代码逻辑复用根目录的公共 ioc
func InitExecuteApp() *ExecuteApp {
	client := ioc.InitEtcdClient()
	registry := ioc.InitRegistry(client)
	executor := ioc.InitExecutor(registry)
	server := InitExecutorServer(executor)
	executeApp := &ExecuteApp{
		Server: server,
	}
	return executeApp
}

// wire.go:

// ExecuteApp 仅包含 Executor 的服务器实例
type ExecuteApp struct {
	Server *grpc.Server
}

// InitExecutorServer 是一个小适配器，将公共的 executor 对象转换为二进制需要的 server
func InitExecutorServer(exec *executor.Executor) *grpc.Server {
	return exec.Server()
}
