// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"context"
	"github.com/Duke1616/ecmdb/api/proto/gen/ecmdb/endpoint/v1"
	"github.com/Duke1616/ecmdb/pkg/policy"
	"github.com/Duke1616/etask/internal/agent"
	"github.com/Duke1616/etask/internal/grpc"
	"github.com/Duke1616/etask/internal/repository"
	"github.com/Duke1616/etask/internal/repository/dao"
	"github.com/Duke1616/etask/internal/service/scheduler"
	"github.com/Duke1616/etask/internal/service/task"
	"github.com/Duke1616/etask/internal/web/executor"
	task2 "github.com/Duke1616/etask/internal/web/task"
	"github.com/Duke1616/etask/ioc"
	grpc2 "github.com/Duke1616/etask/pkg/grpc"
	"github.com/gotomicro/ego/server/egin"
)

// Injectors from wire.go:

func InitSchedulerApp() *SchedulerApp {
	v := ioc.InitGinMiddlewares()
	sdk := policy.NewSDK()
	db := ioc.InitDB()
	taskDAO := dao.NewGORMTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	service := task.NewService(taskRepository)
	taskExecutionLogDAO := dao.NewGORMTaskExecutionLogDAO(db)
	logService := task.NewLogService(taskExecutionLogDAO)
	handler := task2.NewHandler(service, logService)
	client := ioc.InitEtcdClient()
	registry := ioc.InitRegistry(client)
	executorHandler := executor.NewHandler(registry)
	mq := ioc.InitMQ()
	module := agent.InitModule(mq, client)
	webHandler := module.Hdl
	listener := ioc.InitListener()
	component := ioc.InitGinWebServer(v, sdk, handler, executorHandler, webHandler, listener)
	string2 := ioc.InitNodeID()
	taskExecutionDAO := dao.NewGORMTaskExecutionDAO(db)
	taskExecutionRepository := repository.NewTaskExecutionRepository(taskExecutionDAO, taskRepository)
	completeProducer := ioc.InitCompleteProducer(mq)
	executionService := task.NewExecutionService(string2, taskExecutionRepository, service, logService, completeProducer, registry)
	reporterServer := grpc.NewReporterServer(executionService)
	taskServer := grpc.NewTaskServer(service)
	agentServer := grpc.NewAgentServer(taskExecutionRepository, logService)
	server := ioc.InitSchedulerNodeGRPCServer(registry, reporterServer, taskServer, agentServer)
	taskAcquirer := ioc.InitMySQLTaskAcquirer(taskRepository)
	clients := ioc.InitExecutorServiceGRPCClients(registry)
	invoker := ioc.InitInvoker(clients)
	runner := ioc.InitRunner(string2, service, executionService, taskAcquirer, invoker, completeProducer)
	executorNodePicker := ioc.InitExecutorNodePicker(registry)
	iExecModeResolver := ioc.InitExecModeResolver(registry, taskRepository)
	scheduler := ioc.InitScheduler(string2, runner, service, executionService, taskAcquirer, executorNodePicker, iExecModeResolver)
	retryCompensator := ioc.InitRetryCompensator(runner, executionService)
	rescheduleCompensator := ioc.InitRescheduleCompensator(runner, executionService)
	interruptCompensator := ioc.InitInterruptCompensator(clients, executionService)
	completeConsumer := ioc.InitCompleteEventConsumer(mq, service, executionService, taskAcquirer)
	v2 := ioc.InitTasks(retryCompensator, rescheduleCompensator, interruptCompensator, completeConsumer)
	clientConnInterface := ioc.InitECMDBGrpcClient(registry)
	endpointServiceClient := ioc.InitEndpointServiceClient(clientConnInterface)
	schedulerApp := &SchedulerApp{
		Web:         component,
		Server:      server,
		Scheduler:   scheduler,
		Tasks:       v2,
		EndpointSvc: endpointServiceClient,
	}
	return schedulerApp
}

// wire.go:

type SchedulerApp struct {
	Web         *egin.Component
	Server      *grpc2.Server
	Scheduler   *scheduler.Scheduler
	Tasks       []ioc.Task
	EndpointSvc endpointv1.EndpointServiceClient
}

func (s *SchedulerApp) StartTasks(ctx context.Context) {
	for _, t := range s.Tasks {
		go func(t ioc.Task) {
			t.Start(ctx)
		}(t)
	}
}
